import type { ReferenceCompound } from '../schema';

export const retatrutide: ReferenceCompound = {
  id: 'retatrutide',
  name: 'Retatrutide',
  aliases: ['LY3437943', 'LY-3437943'],
  compoundType: 'glp-1',
  category: 'metabolic',
  defaultRoute: 'subq',
  supportedRoutes: ['subq'],
  defaultDoseUnit: 'mg',
  concentrationMode: 'none',
  dosePresets: [
    {
      label: 'Phase 2 trial arm: 1 mg',
      value: 1,
      unit: 'mg',
      intent: 'commonResearchRange',
      sourceNote: 'Studied as a once-weekly phase 2 trial arm; included for source-backed logging context, not as guidance.',
      citationIds: ['pubmed-retatrutide-obesity-phase-2'],
    },
    {
      label: 'Phase 2 trial arm: 4 mg',
      value: 4,
      unit: 'mg',
      intent: 'commonResearchRange',
      sourceNote: 'Studied as a once-weekly phase 2 trial arm; included for source-backed logging context, not as guidance.',
      citationIds: ['pubmed-retatrutide-obesity-phase-2'],
    },
    {
      label: 'Phase 2 trial arm: 8 mg',
      value: 8,
      unit: 'mg',
      intent: 'commonResearchRange',
      sourceNote: 'Studied as a once-weekly phase 2 trial arm; included for source-backed logging context, not as guidance.',
      citationIds: ['pubmed-retatrutide-obesity-phase-2'],
    },
    {
      label: 'Phase 2 trial arm: 12 mg',
      value: 12,
      unit: 'mg',
      intent: 'commonResearchRange',
      sourceNote: 'Studied as a once-weekly phase 2 trial arm; included for source-backed logging context, not as guidance.',
      citationIds: ['pubmed-retatrutide-obesity-phase-2'],
    },
  ],
  vialPresets: [
    {
      label: 'User-labeled container',
      sourceNote: 'No FDA-approved commercial Retatrutide presentation is established; inventory records should use the exact vial, kit, or research label.',
      citationIds: ['lilly-retatrutide-investigational'],
    },
  ],
  beginnerSummary: 'A triple-agonist metabolic peptide in the incretin family. PeptideOS treats it as a high-interest research compound with strong trial signals and unresolved approval, sourcing, and long-term safety questions.',
  researcherDetails: 'Retatrutide (LY3437943) is a lipidated triple agonist of the GLP-1, GIP, and glucagon receptors. Published phase 2 obesity data reported dose-related body-weight reductions through 48 weeks, and Lilly has an active phase 3 TRIUMPH program. It remains investigational in the US, so user inventory should be tracked from actual product labels rather than assumed marketed presentations.',
  mechanism: 'Triple incretin agonism: GLP-1 receptor activation supports satiety and glucose-dependent insulin effects, GIP receptor activation contributes incretin signaling, and glucagon receptor activation is being studied for energy-expenditure and hepatic-metabolic effects. The chronic balance of these pathways remains an active research question.',
  safety: 'Published obesity phase 2 data reported mostly mild-to-moderate gastrointestinal adverse events and dose-dependent heart-rate increases. The compound is still under clinical development, so product quality, authenticity, long-term safety, and individual risk require careful source review outside the app.',
  storage: 'No approved US product label defines consumer storage. Store inventory according to the specific vial, kit, pharmacy, or research supplier documentation attached to the item, and preserve lot/source notes in PeptideOS.',
  referenceProfile: {
    evidenceTier: 'phase-3-topline',
    biohackerBrief: {
      headline: 'A triple-agonist metabolic peptide people are watching because it may push past the current GLP-1/GIP ceiling.',
      whyPeopleCare: [
        'It hits GLP-1, GIP, and glucagon receptors instead of only one or two incretin pathways.',
        'The published phase 2 obesity trial showed unusually large body-weight changes over 48 weeks.',
        'Lilly has phase 3/topline program momentum, but there is still no FDA-approved consumer label.',
      ],
      verifyBeforeUse: [
        'Exact compound name, lot, source, vial amount, concentration, and whether the container is lyophilized or already liquid.',
        'Whether the label says retatrutide/LY3437943 or a vague blend name; do not treat marketing names as identity proof.',
        'Storage instructions from the actual supplier or pharmacy document, not from a different GLP-1 product.',
      ],
      trackInApp: [
        'Inventory by vial or kit so identical-looking vials do not blur together later.',
        'Schedule adherence, missed doses, side-effect notes, appetite/weight trend notes, and dose changes over time.',
        'Reconstitution math only when vial amount and diluent volume are user-confirmed.',
      ],
      realityCheck: 'The clinical Retatrutide story is not a gray-market vial. PeptideOS should help the user track what they actually have, what they actually did, and what is still uncertain.',
    },
    reviewSummary: 'Retatrutide is one of the strongest current examples of a biohacking-relevant compound where evidence is substantial but not settled: published phase 2 human data, company-announced phase 3 results, active additional trials, and no FDA-approved consumer product label.',
    mechanismTargets: [
      'GLP-1 receptor',
      'GIP receptor',
      'glucagon receptor',
    ],
    clinicalEvidence: [
      {
        design: 'phase-2-randomized-controlled-trial',
        population: 'Adults with obesity or overweight plus at least one weight-related condition',
        finding: 'Published phase 2 data reported dose-related body-weight reductions at 24 and 48 weeks, with gastrointestinal events and heart-rate increases among notable safety signals.',
        citationIds: ['pubmed-retatrutide-obesity-phase-2'],
        sourceQuality: 'source-backed',
      },
      {
        design: 'phase-3-program',
        population: 'Adults with obesity, overweight, type 2 diabetes, cardiovascular disease, obstructive sleep apnea, or related trial subgroups',
        finding: 'Lilly reports completed phase 3 studies and additional ongoing TRIUMPH and TRANSCEND-T2D trials; the compound remains under development while regulatory review has not produced an approved US label.',
        citationIds: ['lilly-retatrutide-investigational', 'clinicaltrials-retatrutide-triumph-1', 'clinicaltrials-retatrutide-triumph-5'],
        sourceQuality: 'trial-registry',
        limitations: 'Some phase 3 details are company-announced/topline or trial-registry status rather than an FDA-reviewed label.',
      },
    ],
    safetySignals: [
      'Gastrointestinal adverse events were common in published phase 2 obesity data.',
      'Dose-dependent heart-rate increases were observed in published phase 2 obesity data.',
      'Long-term cardiovascular, renal, hepatic, and maintenance outcomes are still being studied across the broader program.',
      'No approved US commercial label exists, so authenticity and product-quality risks matter for user-entered inventory.',
    ],
    practicalNotes: [
      'Record the exact supplier, lot, vial amount, concentration, and container state from the physical label.',
      'Treat trial-arm values as literature context only; PeptideOS should not convert them into default protocols.',
      'Use schedule and dose logs to audit personal research patterns, missed doses, adverse notes, and inventory depletion.',
      'Attach source documentation to inventory when available so future review is not dependent on memory.',
    ],
    evidenceGaps: [
      'No FDA-approved US prescribing label or consumer storage instructions.',
      'Some phase 3 results are company-announced/topline or not yet reflected in an FDA-approved label.',
      'No head-to-head published outcome trial versus tirzepatide or semaglutide was found in the reviewed app source set.',
      'Community-market products may not match clinical-trial material, concentration, purity, or stability.',
    ],
    regulatoryStatus: {
      status: 'investigational',
      region: 'US',
      summary: 'Lilly describes Retatrutide as not FDA approved and investigational while phase 3 trials evaluate safety and efficacy.',
      citationIds: ['lilly-retatrutide-investigational'],
      sourceQuality: 'source-backed',
    },
    peptideOSActions: [
      'Log labeled doses or ask Peppi to build a schedule from the user-confirmed label without converting trial arms into recommendations.',
      'Track inventory by exact vial, kit, lot, source, and container state.',
      'Calculate concentration only from user-entered vial amount and diluent volume.',
      'Review schedule adherence, inventory depletion, and personal notes over time.',
      'Flag missing label data before adding a vial or schedule.',
    ],
  },
  citations: [
    {
      id: 'pubmed-retatrutide-obesity-phase-2',
      title: 'Triple-Hormone-Receptor Agonist Retatrutide for Obesity - A Phase 2 Trial',
      url: 'https://pubmed.ncbi.nlm.nih.gov/37366315/',
      source: 'The New England Journal of Medicine / PubMed',
      year: 2023,
    },
    {
      id: 'pubchem-retatrutide',
      title: 'Retatrutide compound record',
      url: 'https://pubchem.ncbi.nlm.nih.gov/compound/Retatrutide',
      source: 'PubChem',
      year: 2026,
    },
    {
      id: 'lilly-retatrutide-investigational',
      title: 'What to know about retatrutide',
      url: 'https://www.lilly.com/news/stories/what-to-know-about-retatrutide',
      source: 'Eli Lilly and Company',
      year: 2026,
    },
    {
      id: 'clinicaltrials-retatrutide-triumph-1',
      title: 'TRIUMPH-1: Retatrutide in participants who have obesity or overweight',
      url: 'https://clinicaltrials.gov/study/NCT05929066',
      source: 'ClinicalTrials.gov',
      year: 2026,
    },
    {
      id: 'clinicaltrials-retatrutide-triumph-5',
      title: 'TRIUMPH-5: Retatrutide compared to tirzepatide in adults who have obesity',
      url: 'https://clinicaltrials.gov/study/NCT06662383',
      source: 'ClinicalTrials.gov',
      year: 2026,
    },
  ],
  source: 'bundled',
  curationStatus: 'reviewed',
};
